#!/bin/sh

PROGRAM=$1

testscripts()
{
    pass '' ''
    pass '100' ''
    pass '"text"' ''
    pass '"\t\n\r !\"#$%&'"'"'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^`_abcdefghijklmnopqrstuvwxyz{|}~"' ''
    pass 'null' ''
    pass 'nullnull' ''
    pass 'null null' ''
    pass 'false' ''
    pass 'true' ''
    pass '$a=null'
    pass '$a=100' ''
    pass '$a="text"' ''
    pass '$A="val"' ''
    pass '$0="val"' ''
    pass '$_="val"' ''
    pass '$Text_100="val"' ''
    pass '$"(long) & [special] --> ID"="val"' ''
    pass '$a=100 $a' ''
    pass '$a="text" $a' ''
    pass '$a=100 $a=null $a' ''
    pass '@add(100, 200)' ''
    pass '@merge("this", " & that")' ''
    pass '@write(@freeze(0), 1)' '0'
    pass '@write(@freeze(1), 1)' '1'
    pass '@write(@freeze(123), 1)' '123'
    pass '@write(@freeze(-1), 1)' '-1'
    pass '@write(@freeze(-123), 1)' '-123'
    pass '@write(@freeze(32767), 1)' '32767'
    pass '@write(@freeze(-32767), 1)' '-32767'
    pass '@write(@freeze(0.1), 1)' '0.099990'
    pass '@write(@freeze(0.123), 1)' '0.122985'
    pass '@write(@freeze(-0.1), 1)' '-0.099990'
    pass '@write(@freeze(-0.123), 1)' '-0.122985'
    pass '@write(@freeze(123.456), 1)' '123.455993'
    pass '@write(@freeze(-123.456), 1)' '-123.455993'
    pass '@write(@freeze(32767.999999), 1)' '32767.999984'
    pass '@write(@freeze(-32767.999999), 1)' '-32767.999984'
    pass '@write(@freeze(0.000000), 1)' '0'
    pass '@write(@freeze(-0.000000), 1)' '0'
    pass '@write(@freeze(0.000015), 1)' '0.000015'
    pass '@write(@freeze(-0.000015), 1)' '-0.000015'
    pass '@write(@freeze(0.999999), 1)' '0.999984'
    pass '@write(@freeze(-0.999999), 1)' '-0.999984'
    pass '@write(@freeze(0.999984), 1)' '0.999984'
    pass '@write(@freeze(-0.999984), 1)' '-0.999984'
    pass '@write(@freeze(0.1), 1)' '0.099990'
    pass '@write(@freeze(0.12), 1)' '0.119995'
    pass '@write(@freeze(0.123), 1)' '0.122985'
    pass '@write(@freeze(0.1234), 1)' '0.123397'
    pass '@write(@freeze(0.12345), 1)' '0.123443'
    pass '@write(@freeze(0.123456), 1)' '0.123443'
    pass '@write(@freeze(0.1234567), 1)' '0.123443'
    pass '@write(@freeze(0.12345678), 1)' '0.123443'
    pass '@write(@freeze(0.123456789), 1)' '0.123443'
    pass '@write(@freeze(-0.1), 1)' '-0.099990'
    pass '@write(@freeze(-0.12), 1)' '-0.119995'
    pass '@write(@freeze(-0.123), 1)' '-0.122985'
    pass '@write(@freeze(-0.1234), 1)' '-0.123397'
    pass '@write(@freeze(-0.12345), 1)' '-0.123443'
    pass '@write(@freeze(-0.123456), 1)' '-0.123443'
    pass '@write(@freeze(-0.1234567), 1)' '-0.123443'
    pass '@write(@freeze(-0.12345678), 1)' '-0.123443'
    pass '@write(@freeze(-0.123456789), 1)' '-0.123443'
    pass '@write(@freeze(""), 1)' '""'
    pass '@write(@freeze("text"), 1)' '"text"'
    pass '@write(@freeze("\t\n\r !\"#$%&'"'"'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^`_abcdefghijklmnopqrstuvwxyz{|}~"), 1)' '"\t\n\r !\"#$%&'"'"'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^`_abcdefghijklmnopqrstuvwxyz{|}~"'
    pass '@write(@freeze(null), 1)' 'null'
    pass '@write(@freeze(false), 1)' 'false'
    pass '@write(@freeze(true), 1)' 'true'
    pass '$a=100 @write(@freeze($a), 1)' '100'
    pass '$a="text" @write($a, 1)' 'text'
    pass '$a=true @write(@freeze($a), 1)' 'true'
    pass '$a=100 $a=200 $a=300 @write(@freeze($a), 1)' '300'
    pass '$a=100 $b=$a @write(@freeze($b), 1)' '100'
    pass '$a=100 $a=$a @write(@freeze($a), 1)' '100'
    pass '@write(@freeze(@and(false, false)), 1)' 'false'
    pass '@write(@freeze(@and(false, true)), 1)' 'false'
    pass '@write(@freeze(@and(true, false)), 1)' 'false'
    pass '@write(@freeze(@and(true, true)), 1)' 'true'
    pass '@write(@freeze(@or(false, false)), 1)' 'false'
    pass '@write(@freeze(@or(false, true)), 1)' 'true'
    pass '@write(@freeze(@or(true, false)), 1)' 'true'
    pass '@write(@freeze(@or(true, true)), 1)' 'true'
    pass '@write(@freeze(@not(false)), 1)' 'true'
    pass '@write(@freeze(@not(true)), 1)' 'false'
    pass '@write(@freeze(@add(0, 0)), 1)' '0'
    pass '@write(@freeze(@add(1, 2)), 1)' '3'
    pass '@write(@freeze(@add(123, 456)), 1)' '579'
    pass '@write(@freeze(@add(-1, -2)), 1)' '-3'
    pass '@write(@freeze(@add(-123, -456)), 1)' '-579'
    pass '@write(@freeze(@add(0.1, 0.2)), 1)' '0.299987'
    pass '@write(@freeze(@add(0.123, 0.456)), 1)' '0.578979'
    pass '@write(@freeze(@add(-0.1, -0.2)), 1)' '-0.299987'
    pass '@write(@freeze(@add(-0.123, -0.456)), 1)' '-0.578979'
    pass '@write(@freeze(@add(123.456, 123.456)), 1)' '246.911987'
    pass '@write(@freeze(@add(-123.456, -123.456)), 1)' '-246.911987'
    pass '@write(@freeze(@subtract(0, 0)), 1)' '0'
    pass '@write(@freeze(@subtract(1, 2)), 1)' '-1'
    pass '@write(@freeze(@subtract(123, 456)), 1)' '-333'
    pass '@write(@freeze(@subtract(-1, -2)), 1)' '1'
    pass '@write(@freeze(@subtract(-123, -456)), 1)' '333'
    pass '@write(@freeze(@subtract(0.1, 0.2)), 1)' '-0.100006'
    pass '@write(@freeze(@subtract(0.123, 0.456)), 1)' '-0.333007'
    pass '@write(@freeze(@subtract(-0.1, -0.2)), 1)' '0.100006'
    pass '@write(@freeze(@subtract(-0.123, -0.456)), 1)' '0.333007'
    pass '@write(@freeze(@subtract(123.456, 123.456)), 1)' '0'
    pass '@write(@freeze(@subtract(-123.456, -123.456)), 1)' '0'
    pass '@write(@freeze(@multiply(0, 0)), 1)' '0'
    pass '@write(@freeze(@multiply(1, 2)), 1)' '2'
    pass '@write(@freeze(@multiply(-1, -2)), 1)' '2'
    pass '@write(@freeze(@multiply(0.1, 0.2)), 1)' '0.019989'
    pass '@write(@freeze(@multiply(0.123, 0.456)), 1)' '0.056076'
    pass '@write(@freeze(@multiply(-0.1, -0.2)), 1)' '0.019989'
    pass '@write(@freeze(@multiply(-0.123, -0.456)), 1)' '0.056076'
    pass '@write(@freeze(@multiply(123.456, 123.456)), 1)' '15241.382354'
    pass '@write(@freeze(@multiply(-123.456, -123.456)), 1)' '15241.382354'
    pass '@write(@freeze(@divide(1, 2)), 1)' '0.500000'
    pass '@write(@freeze(@divide(123, 456)), 1)' '0.269729'
    pass '@write(@freeze(@divide(-1, -2)), 1)' '0.500000'
    pass '@write(@freeze(@divide(-123, -456)), 1)' '0.269729'
    pass '@write(@freeze(@divide(0.1, 0.2)), 1)' '0.499954'
    pass '@write(@freeze(@divide(0.123, 0.456)), 1)' '0.269699'
    pass '@write(@freeze(@divide(-0.1, -0.2)), 1)' '0.499954'
    pass '@write(@freeze(@divide(-0.123, -0.456)), 1)' '0.269699'
    pass '@write(@freeze(@divide(123.456, 123.456)), 1)' '1'
    pass '@write(@freeze(@divide(-123.456, -123.456)), 1)' '1'
    pass '@write(@freeze(@modulo(1, 2)), 1)' '1'
    pass '@write(@freeze(@modulo(123, 456)), 1)' '123'
    pass '@write(@freeze(@modulo(-1, -2)), 1)' '-1'
    pass '@write(@freeze(@modulo(-123, -456)), 1)' '-123'
    pass '@write(@freeze(@modulo(123.456, 123.456)), 1)' '0'
    pass '@write(@freeze(@modulo(-123.456, -123.456)), 1)' '0'
    pass '@write(@freeze(@truncate(0)), 1)' '0'
    pass '@write(@freeze(@truncate(1)), 1)' '1'
    pass '@write(@freeze(@truncate(123)), 1)' '123'
    pass '@write(@freeze(@truncate(-1)), 1)' '-1'
    pass '@write(@freeze(@truncate(-123)), 1)' '-123'
    pass '@write(@freeze(@truncate(32767)), 1)' '32767'
    pass '@write(@freeze(@truncate(-32767)), 1)' '-32767'
    pass '@write(@freeze(@truncate(0.1)), 1)' '0'
    pass '@write(@freeze(@truncate(0.123)), 1)' '0'
    pass '@write(@freeze(@truncate(-0.1)), 1)' '0'
    pass '@write(@freeze(@truncate(-0.123)), 1)' '0'
    pass '@write(@freeze(@truncate(123.456)), 1)' '123'
    pass '@write(@freeze(@truncate(-123.456)), 1)' '-123'
    pass '@write(@freeze(@truncate(0.999999)), 1)' '0'
    pass '@write(@freeze(@truncate(-0.999999)), 1)' '0'
    pass '@write(@freeze(@truncate(32767.999999)), 1)' '32767'
    pass '@write(@freeze(@truncate(-32767.999999)), 1)' '-32767'
    pass '@write(@freeze(@equals(null, null)), 1)' 'true'
    pass '@write(@freeze(@equals(null, true)), 1)' 'false'
    pass '@write(@freeze(@equals(null, 100)), 1)' 'false'
    pass '@write(@freeze(@equals(null, "text")), 1)' 'false'
    pass '@write(@freeze(@equals(null, "null")), 1)' 'false'
    pass '@write(@freeze(@equals(false, false)), 1)' 'true'
    pass '@write(@freeze(@equals(true, true)), 1)' 'true'
    pass '@write(@freeze(@equals(false, true)), 1)' 'false'
    pass '@write(@freeze(@equals(true, false)), 1)' 'false'
    pass '@write(@freeze(@equals(true, null)), 1)' 'false'
    pass '@write(@freeze(@equals(true, 100)), 1)' 'false'
    pass '@write(@freeze(@equals(true, "text")), 1)' 'false'
    pass '@write(@freeze(@equals(true, "true")), 1)' 'false'
    pass '@write(@freeze(@equals(100, 100)), 1)' 'true'
    pass '@write(@freeze(@equals(0, 0)), 1)' 'true'
    pass '@write(@freeze(@equals(-100, -100)), 1)' 'true'
    pass '@write(@freeze(@equals(100, 0)), 1)' 'false'
    pass '@write(@freeze(@equals(100, -100)), 1)' 'false'
    pass '@write(@freeze(@equals(100, null)), 1)' 'false'
    pass '@write(@freeze(@equals(100, true)), 1)' 'false'
    pass '@write(@freeze(@equals(100, "text")), 1)' 'false'
    pass '@write(@freeze(@equals(100, "100")), 1)' 'false'
    pass '@write(@freeze(@equals("text", "text")), 1)' 'true'
    pass '@write(@freeze(@equals("text", "")), 1)' 'false'
    pass '@write(@freeze(@equals("text", "word")), 1)' 'false'
    pass '@write(@freeze(@equals("text", "TEXT")), 1)' 'false'
    pass '@write(@freeze(@equals("", "")), 1)' 'true'
    pass '@write(@freeze(@equals("text", null)), 1)' 'false'
    pass '@write(@freeze(@equals("text", true)), 1)' 'false'
    pass '@write(@freeze(@equals("text", 100)), 1)' 'false'
    pass '@write(@freeze(@precedes(null, null)), 1)' 'false'
    pass '@write(@freeze(@precedes(null, true)), 1)' 'true'
    pass '@write(@freeze(@precedes(null, 100)), 1)' 'true'
    pass '@write(@freeze(@precedes(null, "text")), 1)' 'true'
    pass '@write(@freeze(@precedes(false, true)), 1)' 'true'
    pass '@write(@freeze(@precedes(true, false)), 1)' 'false'
    pass '@write(@freeze(@precedes(true, true)), 1)' 'false'
    pass '@write(@freeze(@precedes(true, null)), 1)' 'false'
    pass '@write(@freeze(@precedes(true, 100)), 1)' 'true'
    pass '@write(@freeze(@precedes(true, "text")), 1)' 'true'
    pass '@write(@freeze(@precedes(100, 200)), 1)' 'true'
    pass '@write(@freeze(@precedes(200, 100)), 1)' 'false'
    pass '@write(@freeze(@precedes(100, 100)), 1)' 'false'
    pass '@write(@freeze(@precedes(100, -100)), 1)' 'false'
    pass '@write(@freeze(@precedes(-100, 100)), 1)' 'true'
    pass '@write(@freeze(@precedes(32767.999999, -32767.999999)), 1)' 'false'
    pass '@write(@freeze(@precedes(-32767.999999, 32767.999999)), 1)' 'true'
    pass '@write(@freeze(@precedes(100, null)), 1)' 'false'
    pass '@write(@freeze(@precedes(100, true)), 1)' 'false'
    pass '@write(@freeze(@precedes(100, "text")), 1)' 'true'
    pass '@write(@freeze(@precedes("text", "word")), 1)' 'true'
    pass '@write(@freeze(@precedes("word", "text")), 1)' 'false'
    pass '@write(@freeze(@precedes("text", "text")), 1)' 'false'
    pass '@write(@freeze(@precedes("text", "TEXT")), 1)' 'false'
    pass '@write(@freeze(@precedes("TEXT", "text")), 1)' 'true'
    pass '@write(@freeze(@precedes("text", null)), 1)' 'false'
    pass '@write(@freeze(@precedes("text", 100)), 1)' 'false'
    pass '@write(@freeze(@precedes("text", true)), 1)' 'false'
    pass '@write(@freeze(@succeeds(null, null)), 1)' 'false'
    pass '@write(@freeze(@succeeds(null, true)), 1)' 'false'
    pass '@write(@freeze(@succeeds(null, 100)), 1)' 'false'
    pass '@write(@freeze(@succeeds(null, "text")), 1)' 'false'
    pass '@write(@freeze(@succeeds(false, true)), 1)' 'false'
    pass '@write(@freeze(@succeeds(true, false)), 1)' 'true'
    pass '@write(@freeze(@succeeds(true, true)), 1)' 'false'
    pass '@write(@freeze(@succeeds(true, null)), 1)' 'true'
    pass '@write(@freeze(@succeeds(true, 100)), 1)' 'false'
    pass '@write(@freeze(@succeeds(true, "text")), 1)' 'false'
    pass '@write(@freeze(@succeeds(100, 200)), 1)' 'false'
    pass '@write(@freeze(@succeeds(200, 100)), 1)' 'true'
    pass '@write(@freeze(@succeeds(100, 100)), 1)' 'false'
    pass '@write(@freeze(@succeeds(100, -100)), 1)' 'true'
    pass '@write(@freeze(@succeeds(-100, 100)), 1)' 'false'
    pass '@write(@freeze(@succeeds(32767.999999, -32767.999999)), 1)' 'true'
    pass '@write(@freeze(@succeeds(-32767.999999, 32767.999999)), 1)' 'false'
    pass '@write(@freeze(@succeeds(100, null)), 1)' 'true'
    pass '@write(@freeze(@succeeds(100, true)), 1)' 'true'
    pass '@write(@freeze(@succeeds(100, "text")), 1)' 'false'
    pass '@write(@freeze(@succeeds("text", "word")), 1)' 'false'
    pass '@write(@freeze(@succeeds("word", "text")), 1)' 'true'
    pass '@write(@freeze(@succeeds("text", "text")), 1)' 'false'
    pass '@write(@freeze(@succeeds("text", "TEXT")), 1)' 'true'
    pass '@write(@freeze(@succeeds("TEXT", "text")), 1)' 'false'
    pass '@write(@freeze(@succeeds("text", null)), 1)' 'true'
    pass '@write(@freeze(@succeeds("text", 100)), 1)' 'true'
    pass '@write(@freeze(@succeeds("text", true)), 1)' 'true'
    pass '@write(@type(null), 1)' 'NULL'
    pass '@write(@type(false), 1)' 'BOOLEAN'
    pass '@write(@type(0), 1)' 'NUMBER'
    pass '@write(@type(""), 1)' 'STRING'
    pass '@write(@cast(@cast(null, "NULL"), "STRING"), 1)' 'null'
    pass '@write(@cast(@cast("null", "NULL"), "STRING"), 1)' 'null'
    pass '@write(@cast(@cast(true, "BOOLEAN"), "STRING"), 1)' 'true'
    pass '@write(@cast(@cast("true", "BOOLEAN"), "STRING"), 1)' 'true'
    pass '@write(@cast(@cast(123.456, "NUMBER"), "STRING"), 1)' '123.455993'
    pass '@write(@cast(@cast("123.456", "NUMBER"), "STRING"), 1)' '123.455993'
    pass '@write(@cast(null, "STRING"), 1)' 'null'
    pass '@write(@cast(true, "STRING"), 1)' 'true'
    pass '@write(@cast(123.456, "STRING"), 1)' '123.455993'
    pass '@write(@cast("text", "STRING"), 1)' 'text'
    pass '@write(@freeze(@get("abc", 1)), 1)' '"a"'
    pass '@write(@freeze(@get("abc", 2)), 1)' '"b"'
    pass '@write(@freeze(@get("abc", 3)), 1)' '"c"'
    pass '@write(@freeze(@set("abc", 1, "x")), 1)' '"xbc"'
    pass '@write(@freeze(@set("abc", 2, "x")), 1)' '"axc"'
    pass '@write(@freeze(@set("abc", 3, "x")), 1)' '"abx"'
    pass '@write(@freeze(@set("abc", 1, "")), 1)' '"bc"'
    pass '@write(@freeze(@set("abc", 2, "")), 1)' '"ac"'
    pass '@write(@freeze(@set("abc", 3, "")), 1)' '"ab"'
    pass '@write(@freeze(@set("abc", 1, "123")), 1)' '"123bc"'
    pass '@write(@freeze(@set("abc", 2, "123")), 1)' '"a123c"'
    pass '@write(@freeze(@set("abc", 3, "123")), 1)' '"ab123"'
    pass '@write(@freeze(@unset("abc", 1)), 1)' '"bc"'
    pass '@write(@freeze(@unset("abc", 2)), 1)' '"ac"'
    pass '@write(@freeze(@unset("abc", 3)), 1)' '"ab"'
    pass '@write(@merge("this", " & that"), 1)' 'this & that'
    pass '@write(@merge("this", ""), 1)' 'this'
    pass '@write(@merge("", "that"), 1)' 'that'
    pass '@write(@freeze(@length("")), 1)' '0'
    pass '@write(@freeze(@length("0")), 1)' '1'
    pass '@write(@freeze(@length("0123456789")), 1)' '10'
    pass '$a=100 $b=200 @write(@freeze(@add($a, $b)), 1)' '300'
    pass '$a="this" $b=" & that" @write(@merge($a, $b), 1)' 'this & that'
    pass '$"long id"="found" @write($"long id", 1)' 'found'
    pass '$""="found" @write($"", 1)' 'found'
    pass '$"id"="found" @write($"id", 1)' 'found'
    pass '$id="found" @write($"id", 1)' 'found'
    pass '$"id"="found" @write($id, 1)' 'found'
    pass 'if false { @write("hit", 1) }' ''
    pass 'if true { @write("hit", 1) }' 'hit'
    pass 'if true { if true { @write("hit", 1) } }' 'hit'
    pass 'if true { if false { @write("hit", 1) } }' ''
    pass 'if false { if true { @write("hit", 1) } }' ''
    pass 'if false { if false { @write("hit", 1) } }' ''
    pass '$a=true if $a { @write("hit", 1) }' 'hit'
    pass '$a=false if $a { @write("hit", 1) }' ''
    pass 'if @cast("true", "BOOLEAN") { @write("hit", 1) }' 'hit'
    pass 'if @cast("false", "BOOLEAN") { @write("hit", 1) }' ''
    pass '$a=0 if true { $a=@add($a,1) $a=@add($a,1) $a=@add($a,1) } @write(@freeze($a),1)' '3'
    pass '$msg=if true { "first" "..." "last" } @write(@freeze($msg), 1)' '"last"'
    pass '$msg=if false { "first" "..." "last" } @write(@freeze($msg), 1)' 'null'
    pass '@write(@merge("<", if true { " >" }), 1)' '< >'
    pass 'if true { @write("true", 1) } else { @write("false", 1) }' 'true'
    pass 'if false { @write("true", 1) } else { @write("false", 1) }' 'false'
    pass '$msg=if true { "first" } else { "second" } @write(@freeze($msg), 1)' '"first"'
    pass '$msg=if false { "first" } else { "second" } @write(@freeze($msg), 1)' '"second"'
    pass 'while false { @write("HERE", 1) }' ''
    pass '$i=1 while @precedes($i, 4) { @write(@freeze($i), 1) $i=@add($i, 1) }' '123'
    pass '$i=1 while @precedes($i, 4) { $j=1 while @precedes($j, 4) { @write(@freeze(@multiply($i, $j)), 1) $j=@add($j, 1) } $i=@add($i, 1) }' '123246369'
    lexfail 'NULL' 'NULL'
    lexfail 'unknown' 'unknown'
    lexfail '"missing end' '"missing end'
    lexfail 'missing start"' 'missing start"'
    lexfail '$$$var' '$$$var'
    lexfail '$' '$'
    lexfail '$var-me' '-me'
    lexfail '$-var' '$-var'
    lexfail '$"missing end' '$"missing end'
    lexfail '@not(tru)' 'tru)'
    parsefail '@add(' '('
    parsefail '@add(,' ','
    parsefail '@add(,)' ',)'
    parsefail '@merge("1" "2")' '"1" "2")'
    parsefail '$x="1" $y="2" @merge($x $y)' '$x $y)'
    parsefail '@merge(@freeze(1) @freeze(2))' ') @freeze(2))'
    parsefail 'if' 'if'
    parsefail 'if { }' '{ }'
    parsefail 'if true' 'true'
    parsefail 'if true {' '{'
    parsefail 'if true }' 'true }'
    parsefail 'if true 100' 'true 100'
    parsefail 'if true { 100' '100'
    parsefail 'if true { 100 } else' 'else'
    parsefail 'if true { 100 } else {' '{'
    parsefail 'if true { 100 } else { 200' '200'
    parsefail 'while' 'while'
    parsefail 'while { }' '{ }'
    parsefail 'while false {' '{'
    parsefail 'while false }' 'false }'
    parsefail 'while false 100' 'false 100'
    parsefail 'while false { 100' '100'
    parsefail '$a=' '='
    parsefail '$a=true if $a=false { }' 'false { }'
    parsefail '$a=1 @add($a=2, $a=3)' '2, $a=3)'
    executefail '@add()' 'absent argument'
    executefail '@write()' 'absent argument'
    executefail '@freeze()' 'absent argument'
    executefail '@not(@not())' 'absent argument'
    executefail '$huh' 'absent variable'
    executefail '@huh()' 'absent function'
    executefail '@add(32767, 32767)' 'arithmetic error'
    executefail '@add(1, 32767)' 'arithmetic error'
    executefail '@add(32767, 1)' 'arithmetic error'
    executefail '@subtract(-32767, 32767)' 'arithmetic error'
    executefail '@subtract(-1, 32767)' 'arithmetic error'
    executefail '@subtract(-32767, 1)' 'arithmetic error'
    executefail '@multiply(32767, 32767)' 'arithmetic error'
    executefail '@multiply(32767, -32767)' 'arithmetic error'
    executefail '@multiply(-32767, 32767)' 'arithmetic error'
    executefail '@multiply(-32767, -32767)' 'arithmetic error'
    executefail '@divide(32767, 0.5)' 'arithmetic error'
    executefail '@divide(32767, -0.5)' 'arithmetic error'
    executefail '@divide(-32767, 0.5)' 'arithmetic error'
    executefail '@divide(-32767, -0.5)' 'arithmetic error'
    executefail '@divide(100, 0)' 'arithmetic error'
    executefail '@modulo(100, 0)' 'arithmetic error'
    executefail '@cast(123.456, "NULL")' 'invalid cast'
    executefail '@cast(true, "NULL")' 'invalid cast'
    executefail '@cast("text", "NULL")' 'invalid cast'
    executefail '@cast(null, "BOOLEAN")' 'invalid cast'
    executefail '@cast(123.456, "BOOLEAN")' 'invalid cast'
    executefail '@cast("text", "BOOLEAN")' 'invalid cast'
    executefail '@cast(null, "NUMBER")' 'invalid cast'
    executefail '@cast(true, "NUMBER")' 'invalid cast'
    executefail '@cast("text", "NUMBER")' 'invalid cast'
    executefail '@cast(null, "WRONG")' 'unknown type'
    executefail '@add' 'unexpected reference type'
    executefail 'if true { "before" @divide(100, 0) "after" }' 'arithmetic error'
    executefail 'if @divide(100, 0) { $missing }' 'arithmetic error'
    executefail 'while true { "before" @divide(100, 0) "after" }' 'arithmetic error'
    executefail 'while @divide(100, 0) { $missing }' 'arithmetic error'
    executefail '@write(@freeze(@get("abc", 0)), 1)' 'absent key'
    executefail '@write(@freeze(@get("abc", 4)), 1)' 'absent key'
    executefail '@write(@freeze(@set("abc", 0, "x")), 1)' 'absent key'
    executefail '@write(@freeze(@set("abc", 4, "x")), 1)' 'absent key'
    executefail '@write(@freeze(@set("abc", 0, "")), 1)' 'absent key'
    executefail '@write(@freeze(@set("abc", 4, "")), 1)' 'absent key'
    executefail '@write(@freeze(@set("abc", 0, "xxx")), 1)' 'absent key'
    executefail '@write(@freeze(@set("abc", 4, "xxx")), 1)' 'absent key'
    executefail '@write(@freeze(@unset("abc", 0)), 1)' 'absent key'
    executefail '@write(@freeze(@unset("abc", 4)), 1)' 'absent key'
}

lexfail()
{
    fail "$1" "langnd: failed to lex code
    [hint] $2"
}

parsefail()
{
    fail "$1" "langnd: failed to parse code
    [hint] $2"
}

executefail()
{
    fail "$1" "langnd: failed to execute code
    [hint] $2"
}

pass()
{
    testscript "$1" "$2" 0 1
}

fail()
{
    testscript "$1" "$2" 1 2
}

testscript()
{
    text=$1
    expected_output=$2
    expected_code=$3
    capture_stream=$4

    if [ $capture_stream = 1 ]
    then
        actual_output=`$PROGRAM -t "$text" 2>/dev/null`
        actual_code=$?
    elif [ $capture_stream = 2 ]
    then
        actual_output=`$PROGRAM -t "$text" 2>&1`
        actual_code=$?
    else
        printf 'failed to capture stream\n' 1>&2
        exit 1
    fi

    if [ $actual_code != $expected_code ]
    then
        printf 'failed to match exit code of test case\n' 1>&2
        printf '    [source] %s\n' "$text" 1>&2
        printf '    [expected] %d\n' $expected_code 1>&2
        printf '    [actual] %d\n' $actual_code 1>&2
        exit 1
    fi

    if [ "$actual_output" != "$expected_output" ]
    then
        printf 'failed to match stream of test case\n' 1>&2
        printf '    [source] %s\n' "$text" 1>&2
        printf '    [expected] %s\n' "$expected_output" 1>&2
        printf '    [actual] %s\n' "$actual_output" 1>&2
        exit 1
    fi
}

testscripts
