suite 'statement/assignment'

pass '$a=null'
pass '$a=100' ''
pass '$a="text"' ''
pass '$A="val"' ''
pass '$0="val"' ''
pass '$_="val"' ''
pass '$Text_100="val"' ''
pass '$"(long) & [special] --> ID"="val"' ''
pass '$a=100 $a' ''
pass '$a="text" $a' ''
pass '$a=100 $a=null $a' ''
pass '$a=100 @write(@freeze($a), 1)' '100'
pass '$a="text" @write($a, 1)' 'text'
pass '$a=true @write(@freeze($a), 1)' 'true'
pass '$a=100 $a=200 $a=300 @write(@freeze($a), 1)' '300'
pass '$a=100 $b=$a @write(@freeze($b), 1)' '100'
pass '$a=100 $a=$a @write(@freeze($a), 1)' '100'
pass '$a=100 $b=200 @write(@freeze(@add($a, $b)), 1)' '300'
pass '$a="this" $b=" & that" @write(@merge($a, $b), 1)' 'this & that'
pass '$"long id"="found" @write($"long id", 1)' 'found'
pass '$""="found" @write($"", 1)' 'found'
pass '$"id"="found" @write($"id", 1)' 'found'
pass '$id="found" @write($"id", 1)' 'found'
pass '$"id"="found" @write($id, 1)' 'found'

parsefail '$a=' '='

executefail '$huh' 'absent variable'
