suite 'statement/branch'

pass 'if false { @write("hit", 1) }' ''
pass 'if true { @write("hit", 1) }' 'hit'
pass 'if true { if true { @write("hit", 1) } }' 'hit'
pass 'if true { if false { @write("hit", 1) } }' ''
pass 'if false { if true { @write("hit", 1) } }' ''
pass 'if false { if false { @write("hit", 1) } }' ''
pass '$a=true if $a { @write("hit", 1) }' 'hit'
pass '$a=false if $a { @write("hit", 1) }' ''
pass 'if @cast("true", "BOOLEAN") { @write("hit", 1) }' 'hit'
pass 'if @cast("false", "BOOLEAN") { @write("hit", 1) }' ''
pass '$a=0 if true { $a=@add($a,1) $a=@add($a,1) $a=@add($a,1) } @write(@freeze($a),1)' '3'
pass '$msg=if true { "first" "..." "last" } @write(@freeze($msg), 1)' '"last"'
pass '$msg=if false { "first" "..." "last" } @write(@freeze($msg), 1)' 'null'
pass '@write(@merge("<", if true { " >" }), 1)' '< >'
pass 'if true { @write("true", 1) } else { @write("false", 1) }' 'true'
pass 'if false { @write("true", 1) } else { @write("false", 1) }' 'false'
pass '$msg=if true { "first" } else { "second" } @write(@freeze($msg), 1)' '"first"'
pass '$msg=if false { "first" } else { "second" } @write(@freeze($msg), 1)' '"second"'

parsefail 'if' 'if'
parsefail 'if { }' '{ }'
parsefail 'if true' 'true'
parsefail 'if true {' '{'
parsefail 'if true }' 'true }'
parsefail 'if true 100' 'true 100'
parsefail 'if true { 100' '100'
parsefail 'if true { 100 } else' 'else'
parsefail 'if true { 100 } else {' '{'
parsefail 'if true { 100 } else { 200' '200'
parsefail '$a=true if $a=false { }' 'false { }'

executefail 'if true { "before" @divide(100, 0) "after" }' 'arithmetic error'
executefail 'if @divide(100, 0) { $missing }' 'arithmetic error'
